#!/usr/bin/env php
<?php

// Autoload
require 'vendor/autoload.php';

// Prepare Packages
use Symfony\Component\Dotenv\Dotenv;

// Prepare App Classes
use Pillar\App\Console;

// Register and load .env
$dotenv = new Dotenv();
$dotenv->load(__DIR__ . '/.env');

// Include custom commands
include 'App/ConsoleCommands/ExampleCommand.php';

// Run Console
new Console([
    // Add custom commands here
    new ExampleCommand()
]);
